### ISSUE TITLE
Support self-signed certificates

### ISSUE THREAD

**Issue by ricardoapl** [k3rnelpan1c-dev/uptime-kuma-helm#138]
PostgreSQL Monitor fails when connecting to target with self-signed certificate

There's no option as of now in https://github.com/louislam/uptime-kuma to ignore TLS/SSL errors in PostgreSQL Monitor

However, uptime-kuma supports trusting additional certificates specified in a single file with `NODE_EXTRA_CA_CERTS`

Suggestion is to support such use case as described in https://github.com/louislam/uptime-kuma/issues/1380#issuecomment-1109481258

See also
- https://github.com/louislam/uptime-kuma/wiki/Environment-Variables
- https://nodejs.org/api/cli.html#node_extra_ca_certsfile

**Comment by LoZio** [comment]
I have the same problem. I have a lot of embedded devices with self signed certificates, with no hierarchy, just the certificate itself. You cannot add the single certificates with the "add a custom CA" method, because it does not work in Kuma. It is a problem with the application itself, not the container.
I entered the container, trusted the single certificate as a CA and run update-ca-certificate. The curl command from the shell now recognises the self signed certificate as valid. I used the NODE_EXTRA_CA_CERTS to load the certificates from a mapped file but it still doesn't work. I also added to the same extra-certs file a couple of real internal CAs and it considers valid the certificates from those CAs.
So it is a limitation in validating self-signed certificates alone.
It should be possible to use the flag to skip TLS errors and still be able to check the expiration date (like curl -k). It seems a forced limitation with no benefits, still the ability to validate self signed certificates by trusting them as CA should work as it does in any PKI tool.
